### PR TITLE
Migrate from java to kotlin in imagecropview module except ImageCropView

### PR DESCRIPTION
**Pull request by NeoMindStd**
- Upgrade versions of gradle and kotlin
 - Delete ApplicationTest.java in androidTest
 - [x] Build and run success

### CODE REVIEW

**Comment by helloyako** [comment]
This is the highest priority in my mind. but I haven't do that yet :(
Actuallty, I don't know kotlin well now. So I will just check build and basic function and then merge that.

Thank you so much for this PR :)

**Comment by helloyako** [comment]
@NeoMindStd 
I've tried test but zoom in/out is not working.
It's serious problem.
Could you check this?

**Comment by NeoMindStd** [comment]
@helloyako 
Sure, I'll check it.

**Comment by NeoMindStd** [comment]
> @helloyako
> Sure, I'll check it.

I checked the problem you mentioned, and it happened to me too.
[I tried to solve the problem, but it was not resolved](https://github.com/NeoMindStd/android-imagecropview/commit/8a27fd9fabd44a7ef5935a9029827ae94aa427d5#diff-d05b8861d02f4cc0c47bc78bc1e6e89d31f47761638835c010b7328e105a24a4).
so I exclude ImageCropView, and forced push the commit 01ef1b0a06b22aa22787545a5b531944f3a0f139.

**Pull request merged**
